def func():
    N=int(input('Enter number'))
    if(64<=N<128):
        N==N-64
        if(N>0):
            a=1
        else:a=0
    if(32<=N<64):
        N==N-32
        if(N>0):
            b=1
        else:b=0
    if(16<=N<32):
        N==N-16
        if(N>0):
            c=1
        else:c=0
    if(8<=N<16):
        N==N-8
        if(N>0):
            d=1
        else:d=0
    if(4<=N<8):
        N==N-4
        if(N>0):
            e=1
        else:e=0
    if(2<=N<4):
        N==N-2
        if(N>0):
            f=1
        else:f=0
    if(1<=N<2):
        N==N-1
        if(N>0):
            g=1
        else:g=0
        a=int(a)
        b=int(b)
        c=int(c)
        d=int(d)
        e=int(e)
        f=int(f)
        g=int(g)
        h-int(h)
    print(a,b,c,d,e,f,g)
