def func():
    g=0
    N=int(input('Enter number'))
    for N in range(0,128):
        if(N>=64):
            N=N-64
            if(N<0):
                a=0
            else:a=1
        elif(32<=N<64):
            N=N-32
            if(N<0):
                b=0
            else:b=1
        elif(16<=N<32):
            N=N-16
            if(N<0):
                c=0
            else:c=1
         elif(8<=N<16):
             N=N-8
             if(N<0):
                 d=0
            else:d=1
         elif(4<=N<8):
            N=N-4
            if(N<0):
                 e=0
            else:e=1
          elif(2<=N<4):
             N=N-2
             if(N<0):
                  f=0
             else:f=1
           elif(1<=N<2):
              N=N-1
              if(N<0):
                   h=0
              else:h=1
    print(g,a,b,c,d,e,f,h)
